### ISSUE TITLE
js file destination ?

### ISSUE THREAD

**Issue by mariantanase** [thexmanxyz/Cookie-Consent-Neo-Gantry#1]
Hi,
Congrats for your great work!
I think is the most complex atom I've ever seen :)
Where should the Cookie Consent JS file be inserted? If solving a bug, the presence of this file should not be optional, I think.

**Comment by thexmanxyz** [comment]
@mariantanase Hey and thanks, I really appreciate. It's a bug in the Cookie Consent Javascript API and it has been reported to the corresponding Github repository. So I still think optional is the best way to go because not everyone wants to rely on the non CDN version and it must be fixed there, so I included just a fix until it gets fixed in the API, see also [Bug #170 CC](https://github.com/insites/cookieconsent/issues/170)

If you want to use the fix you can simply drag it anywhere where you can access it from the atom. However i suggest the following folder "/templates/[theme]/custom/js". After that *Enable local JS* and add "templates/[theme]/custom/js/cookieconsent.3.0.4_mod.min.js" to *Local JS Path*. Replace [theme] with your currently used Gantry theme.

If you have any troubles please feel free to report back.
