### ISSUE TITLE
Changing Banner Palette

### ISSUE THREAD

**Issue by mariantanase** [thexmanxyz/Cookie-Consent-Neo-Gantry#3]
When I change the combination from Banner Palette, the "Popup BG Color" and "Button Bg Color" values, remain unchanged (on backend). This is a normal behaviour ?
Anyway, on frontend the colours are changed, and this is ok.
![banner-palette](https://user-images.githubusercontent.com/3976174/31771569-e5de90f8-b4dc-11e7-9e0b-f656c681e3ae.png)

**Comment by thexmanxyz** [comment]
@mariantanase Hello, "Banner Palette" and everything after "Enable Custom Colors" works independent of each other. Banner Palette are presets (which I will rename with the next release to prevent confusion) and the color values are just an option to define customized colors, which are used on activation of the checkbox.

The behaviour you noticed is intended by design. The color fields are not intended to change on a "Banner Palette" change. However I will take a look if this can be done but I think this is not possible because it's not directly supported by Gantry to react on GUI change events within a Particle / Atom backend. However I leave this one open until I have checked this. Did you notice such an event relationship in an other particle? If so it must be possible but I have not seen it tbh.

**Comment by mariantanase** [comment]
ok, understand.
I thought this approach was possible, because I saw that when you change presets in gantry admin, the colors (the variables) change automatically.

**Comment by thexmanxyz** [comment]
@mariantanase I didn't have the time to check on that however I will do it. the real question is not possibility because done can be anything ;). Much more is the intended boundaries imposed by Gantry. Because a lot of things can be done but they will break on template updates or are difficult to install. but not to much yet I will investigate because this would generally improve usability and your idea/approach sounds very intuitive to me :)

**Comment by thexmanxyz** [comment]
@mariantanase 

The naming for palette was changed to preset as of for all language were it was wrong like discussed earlier.

https://github.com/thexmanxyz/Cookie-Consent-Neo-Gantry/commit/49aa427cca48c14263fbcdcb7bacb5252d16e8ac

The changing of fields in dependence of each other is not supported for Atoms and Particles. I can't maintain this feature without to many drawbacks. It's necessary that Gantry adds here generic optionss to attach events or an other sophisticated solution because otherwise the Atom install would get overcomplicated. 

TBH I also don't want a hacky solution. so we have to stick with it as it is.

/closed
